# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "p6k8FNdg9jgMhsat3mWULRZ8XbaeAjihm+dFlco5mmwBDwaLcNkiBHhk9ur6PzWWfQqK9h2EzYKFpnQ63lwwaHlDLbcq373XG8prQ1FokX8nJs9HzuoIjjZRuZn/nVok4GhX5SClrWLU87aOM6/6k/Wo9TTxz4mP5aFiuFlcgMz+b7vUpkIIt8avrNHNU5eWXieIJ9F7sa7V5UU9F0mey7JJQEwQjxFSpgKNvaT0ui6ZJc7rh3ad1vwv+97XDV+l+e9gfw95JA48cjUtRWqO8GiiqpsvTCLhggCvUF8x2kG6MVGnCC+/qlzpZXa1Iln5/gn+J0ZkEHDPkLTMqtc359dle9Oph7wCsHa7/Is+DrtD/uVuv5T4SkYYvudEPFOBy/2wzWkg5+JS+++zP8z/4y4oGsrT92LDBX1JhhZqrOxZxnNFrFWDqCG9CRIMsNpAhitAT0vwqW8s5MsHgStboadRUAJXsvwZJjFyiYqFQtUl2UUZ9iTACdcZK2E4XGyBIRupG3AwtM4OV6SICGiHcl7xkPLUsG/dgweS1VPKeCEHvNPlDz6qPCUbI9mASZKSCiXt7BMJSG3VJx2Ove1ZVmbfxm8UWfID9MI8+yTy/7vMA9iY0RlQZSNQy88a4qTBq1SpVzmFoG0FmSPNt9jDPwitPo7VIrZjfhCFX8EqvVU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
