travis:
  secure:
    BINSTAR_TOKEN: p6k8FNdg9jgMhsat3mWULRZ8XbaeAjihm+dFlco5mmwBDwaLcNkiBHhk9ur6PzWWfQqK9h2EzYKFpnQ63lwwaHlDLbcq373XG8prQ1FokX8nJs9HzuoIjjZRuZn/nVok4GhX5SClrWLU87aOM6/6k/Wo9TTxz4mP5aFiuFlcgMz+b7vUpkIIt8avrNHNU5eWXieIJ9F7sa7V5UU9F0mey7JJQEwQjxFSpgKNvaT0ui6ZJc7rh3ad1vwv+97XDV+l+e9gfw95JA48cjUtRWqO8GiiqpsvTCLhggCvUF8x2kG6MVGnCC+/qlzpZXa1Iln5/gn+J0ZkEHDPkLTMqtc359dle9Oph7wCsHa7/Is+DrtD/uVuv5T4SkYYvudEPFOBy/2wzWkg5+JS+++zP8z/4y4oGsrT92LDBX1JhhZqrOxZxnNFrFWDqCG9CRIMsNpAhitAT0vwqW8s5MsHgStboadRUAJXsvwZJjFyiYqFQtUl2UUZ9iTACdcZK2E4XGyBIRupG3AwtM4OV6SICGiHcl7xkPLUsG/dgweS1VPKeCEHvNPlDz6qPCUbI9mASZKSCiXt7BMJSG3VJx2Ove1ZVmbfxm8UWfID9MI8+yTy/7vMA9iY0RlQZSNQy88a4qTBq1SpVzmFoG0FmSPNt9jDPwitPo7VIrZjfhCFX8EqvVU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
