travis:
  secure:
    BINSTAR_TOKEN: f4VLcZkZa+cXYUS7tH0UK+oB1cIUkB3RO6sEQI+ak9SHvOxkahBcNQe46FOarob0ohB1POWgh9LTOOuhHbJWl1/yaOUlkXbcnCvOG/puPDf+xTyJ9Pr6mygGjNHeAb90RbNOjDS/2sKlU/6yeS1W9GcinNUKbfKx0I0pDOiUd6g77bugIMqqJgaCxBw6lUj+WBTqkpn+GMVLhj+DuZVJi3ApjK8oqBWpHegC4DmobNDMV+AqKEfUHgQ90kd8nnKWBcHg3jGl46MohTqjI7ATsmmUl1BUyUFxsKskTZz3qjaPJjNgVU5AqqDjAoR9H7mT/FW8PZfe7OYwSvwm7zthMIvzRCBCP8eF1dNiPNdjfyJzyhtsvaf6r7xxrOdhL3LwPqulE4kcvSFCMTOAfTKn2HP6EUHV44pJvDtDhr+PK/0JnNgOPPRYoTcJGqhZDrCf3hsrfDaENv7pZURT0KzVsG2zT6ZLNwyBib/aW1CSjzHoWzaE9X3lP048F81uJJjRnrvNy7Bnrvu6eNadtjyxd504L36YxZKXqK6oiALRBp2Zr4cAnGS5IA61o9lcVm9UF4mrFLQr4ae6H8AzXY3tsrRtePzZBnB/XWIrUdpjR7E/KH38rXBju9qGJbWsgritRa16/Q7ouIuKIK9/c/eUNVgdADu4Mxl/2GFFwqXhuFc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
