travis:
  secure:
    BINSTAR_TOKEN: t14n4o9moayA7bEhGoWdQdvV+t9rfO/NXLuckl+qzxKfDmReCvKjxTBW4mZoPOHB+EmSmrH/7I+xDECZ/AjXsujNVGEJLWo8V/RsbK70vSb+Yt8zvg+CYPUEv+abzv3poGnW/ssC0CBHRN8sj4X/tr6ONY59PpqJphREgtKBd+ehsXsGt8Mhkbs1749Ous72PmVJ+fp1fbff1MoWubWh4R3Lv0zxqNNctO+5OBg5TnnIYezdD9ahkeCeFoJVPFOvyavRr/NgtweuC+p5RYCB48jRbQbcta0pDyIfKzOdk5EUGukoT2rgfLY7otqNg1OnGms9uMnps/oFcj71B4ocBbgqH6xTWvMGnreKXtdamwxfW1alj+B1jme8sXcazEwZqhBl8/0wqwrjxinxoZja9I8QI4KOpqAT0/l9FouYU/OegfaL2OsTdrEcFmrgzbqrhfL/A1c2mn53/vAzEqLRyGi6vB6a7GtK1qSLcGMyyGqAV337RGZ9mB6uGEkz55L88DzOCjLtW51CERT7eA8VBGmISxau+J8AOhEWjtOvLf9OapoVF9VDlvep1mVl2b1iZToQ/eUWsfXtcJ31I4T3T0TUrCOxhdvDgqRCYeQboA9VTRxSbDykfL5Z/2rRtj5bEJwaXOxecOL18WA1M0H75brcInxbnGVQKPz5UD3A7xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
